on:
  push:
    paths:
      - 'docs/**'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  pull_request:
    paths:
      - 'docs/**'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  schedule:
  - cron: "0 0 12 * *"

name: check-links

jobs:
  check_links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4


      - name: Remove files that do not need to have their links checked
        run: | 
          rm inst/extdata/compute_1.md
          rm inst/extdata/storage_1.md

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
